CREATE DATABASE windowsXP;

USE windowsXP;

CREATE TABLE usuario (
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(45),
usuario CHAR(20),
senha VARCHAR(20),
avatar VARCHAR(10))
AUTO_INCREMENT = 1000;

SELECT * FROM usuario;